version: '3.8'

services:
  # Your normal application service
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network
    command: python main.py
  
  # Development shell service
  app-shell:
    build: .
    stdin_open: true  # equivalent to -i
    tty: true         # equivalent to -t
    volumes:
      - .:/app
    networks:
      - app-network
    profiles:
      - dev
    command: bash

networks:
  app-network:
    driver: bridge
