version: '3.8'

services:
  # Normal application service
  app:
    build: .
    volumes:
      - .:/app
    networks:
      - app-network
    profiles:
      - prod
    command: python src/main.py --help
  
  # Development shell service
  app-shell:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    networks:
      - app-network
    profiles:
      - dev
    command: bash

networks:
  app-network:
    driver: bridge
